### ISSUE TITLE
UserController 구현 -1

### ISSUE THREAD

**Issue by namtndus** [codestates/Buddy#10]
### ISSUE
- Group:  `client`, `server`, `sr`
- Type: `bug`, `feature`, `delete`
- Detail: fix actions from client redux

### TODO
1. [ ] user login 구헌
2. [ ] user logout 구현
3. [ ] user delete 구현

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 2.5h`
- Group : `server`
- Sprint: `Sprint__2__`
- Urgency: `Middle`
