### ISSUE TITLE
UserController 구현 -2 

### ISSUE THREAD

**Issue by namtndus** [codestates/Buddy#11]
### ISSUE
- Group:  `server`
- Type: `bug`, `feature`
- Detail: fix actions from client redux

### TODO
1. [ ] 이메일 인증 구현
2. [ ] 별명 중복 확인 구현
3. [ ] 회원가입 구현
4. [ ] 토큰 유효기간 확인
5. [ ] 토큰 재발급 확인

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 3h`
- Group : `server`
- Sprint: `Sprint__2__`
- Urgency: `Middle`
